# Generated by Django 3.2.9 on 2021-12-11 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=30)),
                ('event_catagory', models.CharField(max_length=30)),
                ('event_startdate', models.DateTimeField()),
                ('event_enddate', models.DateTimeField()),
            ],
        ),
    ]
