# Generated by Django 3.2.9 on 2022-01-23 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contestant',
            name='contestant_detail',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='event',
            name='event_detail',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='contestant',
            name='contestant_image',
            field=models.ImageField(upload_to='contestantimages/'),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_enddate',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_image',
            field=models.ImageField(upload_to='eventimages/'),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_startdate',
            field=models.DateField(),
        ),
    ]
