# Generated by Django 3.2.9 on 2021-12-11 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_enddate',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_startdate',
            field=models.CharField(max_length=20),
        ),
    ]
