# Generated by Django 3.2.9 on 2022-01-02 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='voted',
            old_name='user',
            new_name='voting_user',
        ),
    ]
