# Generated by Django 3.2.9 on 2021-12-20 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20211211_2125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_enddate',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_startdate',
            field=models.DateTimeField(blank=True),
        ),
    ]
