# Generated by Django 3.2.9 on 2022-01-17 07:17

import autoslug.fields
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20220114_2240'),
    ]

    operations = [
        migrations.AddField(
            model_name='voted',
            name='event',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='myapp.event'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='event',
            name='event_enddate',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_startdate',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, populate_from='event_name'),
        ),
    ]
