# Generated by Django 3.2.9 on 2022-01-24 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_auto_20220124_0906'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='event_completed',
            field=models.BooleanField(default=False),
        ),
    ]
