# Generated by Django 3.2.9 on 2021-12-23 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_auto_20211220_0904'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_enddate',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_startdate',
            field=models.CharField(max_length=30),
        ),
    ]
