# Generated by Django 3.2.9 on 2021-12-24 07:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_auto_20211223_1141'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contestant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contestant_name', models.CharField(max_length=30)),
                ('contestant_id', models.CharField(max_length=30)),
                ('contestant_image', models.ImageField(upload_to='')),
                ('contestant_age', models.CharField(max_length=30)),
                ('contentant_height', models.CharField(max_length=30)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.event')),
            ],
        ),
    ]
