# Generated by Django 3.2.9 on 2022-01-24 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_event_event_completed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='event_completed',
        ),
    ]
