# Generated by Django 3.2.9 on 2022-01-21 10:21

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_alter_voted_voting_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='voted',
            name='voting_user',
        ),
        migrations.AddField(
            model_name='voted',
            name='voting_user_id',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), default=[], size=None),
            preserve_default=False,
        ),
    ]
