# Generated by Django 3.2.9 on 2021-12-25 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_contestant'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='event_image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='contestant',
            name='contestant_id',
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='contestant',
            name='contestant_image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
