# Generated by Django 3.2.9 on 2022-01-02 08:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_auto_20211225_1358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contestant',
            name='contestant_image',
            field=models.ImageField(blank=True, null=True, upload_to='contestantimages/'),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_image',
            field=models.ImageField(blank=True, null=True, upload_to='eventimages/'),
        ),
        migrations.CreateModel(
            name='Voted',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_voted', models.BooleanField(default=False)),
                ('count', models.IntegerField()),
                ('contestant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.contestant')),
            ],
        ),
    ]
